export enum FailureReason {
  //Stripe
  CHECKOUT_SESSION_EXPIRED = 'CHECKOUT_SESSION_EXPIRED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_CANCELED = 'PAYMENT_CANCELED',

  //Staff
  WRONG_AMOUNT = 'WRONG_AMOUNT',
  WRONG_PAYMENT_METHOD = 'WRONG_PAYMENT_METHOD',
  CUSTOMER_CANCELLED = 'CUSTOMER_CANCELLED',
  DUPLICATE_PAYMENT = 'DUPLICATE_PAYMENT',
}
