export enum PaymentErrorCode {
  PAYMENT_FORBIDDEN = 'PAYMENT_FORBIDDEN',
  PAYMENT_NOT_FOUND = 'PAYMENT_NOT_FOUND',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_ALREADY_REFUNDED = 'PAYMENT_ALREADY_REFUNDED',
  PAYMENT_ALREADY_FINALIZED = 'PAYMENT_ALREADY_FINALIZED',
}
