export enum PaymentStatus {
  PENDING = 'PENDING',
  PROCESSING = "PROCESSING",
  COMPLETED = 'COMPLETED',
  PAID = 'PAID',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
}
