export const RMQ_SERVICE = 'RMQ_SERVICE';
export const STRIPE_CLIENT = 'STRIPE_CLIENT'
export const ORDERS_EVENTS_CLIENT = 'ORDERS_EVENTS_CLIENT';
export const ORGANIZATION_SERVICE = 'ORGANIZATION_SERVICE';

export const ORGANIZATION_EVENTS_CLIENT = 'ORGANIZATION_EVENTS_CLIENT';

