export enum StripeConnectErrorCode {
  ACCOUNT_ALREADY_LINKED = 'ACCOUNT_ALREADY_LINKED',
  ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND',
  INVALID_STRIPE_ACCOUNT = 'INVALID_STRIPE_ACCOUNT',
  STRIPE_API_ERROR = 'STRIPE_API_ERROR',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
